[2024-12-26 16:07:20,032] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:07:09.002100+00:00 [None]>
[2024-12-26 16:07:20,045] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:07:09.002100+00:00 [None]>
[2024-12-26 16:07:20,046] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:07:20,046] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 16:07:20,046] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:07:20,058] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T16:07:09.002100+00:00
[2024-12-26 16:07:20,065] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T16:07:09.002100+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpie24jmeo', '--error-file', '/tmp/tmp_74034sk']
[2024-12-26 16:07:20,062] {standard_task_runner.py:52} INFO - Started process 254 to run task
[2024-12-26 16:07:20,065] {standard_task_runner.py:77} INFO - Job 15: Subtask task_zero
[2024-12-26 16:07:20,101] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T16:07:09.002100+00:00 [running]> on host d88713c29571
[2024-12-26 16:07:20,142] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:07:09.002100+00:00
[2024-12-26 16:07:20,143] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 16:07:20,144] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 16:07:20,150] {subprocess.py:75} INFO - Output:
[2024-12-26 16:07:20,776] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 16:07:20,823] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-26 16:07:20,828] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-26 16:07:23,412] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 16:07:23,440] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T160709, start_date=20241226T160720, end_date=20241226T160723
[2024-12-26 16:07:23,457] {local_task_job.py:151} INFO - Task exited with return code 1
