[2024-12-26 16:18:47,034] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2024-12-26T16:16:06.432677+00:00 [None]>
[2024-12-26 16:18:47,050] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2024-12-26T16:16:06.432677+00:00 [None]>
[2024-12-26 16:18:47,050] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:18:47,051] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-26 16:18:47,052] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:18:47,061] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2024-12-26T16:16:06.432677+00:00
[2024-12-26 16:18:47,064] {standard_task_runner.py:52} INFO - Started process 1281 to run task
[2024-12-26 16:18:47,066] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_one', '2024-12-26T16:16:06.432677+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpaoeqakos', '--error-file', '/tmp/tmpeejqahpl']
[2024-12-26 16:18:47,068] {standard_task_runner.py:77} INFO - Job 18: Subtask task_one
[2024-12-26 16:18:47,102] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_one 2024-12-26T16:16:06.432677+00:00 [running]> on host d88713c29571
[2024-12-26 16:18:47,143] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:16:06.432677+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T16:16:06.432677+00:00
[2024-12-26 16:18:47,225] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1a.html
[2024-12-26 16:18:47,226] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:19:02,234] {logging_mixin.py:104} INFO - m1a.html
[2024-12-26 16:19:02,235] {logging_mixin.py:104} INFO - Wrote file: m1a.html
[2024-12-26 16:19:02,310] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1b.html
[2024-12-26 16:19:02,311] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:19:17,325] {logging_mixin.py:104} INFO - m1b.html
[2024-12-26 16:19:17,326] {logging_mixin.py:104} INFO - Wrote file: m1b.html
[2024-12-26 16:19:17,386] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1c.html
[2024-12-26 16:19:17,386] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:19:32,398] {logging_mixin.py:104} INFO - m1c.html
[2024-12-26 16:19:32,399] {logging_mixin.py:104} INFO - Wrote file: m1c.html
[2024-12-26 16:19:32,473] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2a.html
[2024-12-26 16:19:32,474] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:19:47,487] {logging_mixin.py:104} INFO - m2a.html
[2024-12-26 16:19:47,488] {logging_mixin.py:104} INFO - Wrote file: m2a.html
[2024-12-26 16:19:47,553] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2b.html
[2024-12-26 16:19:47,554] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:20:02,560] {logging_mixin.py:104} INFO - m2b.html
[2024-12-26 16:20:02,561] {logging_mixin.py:104} INFO - Wrote file: m2b.html
[2024-12-26 16:20:02,634] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2c.html
[2024-12-26 16:20:02,634] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:20:12,741] {local_task_job.py:199} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-26 16:20:12,743] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 1281
[2024-12-26 16:20:12,744] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-26 16:20:12,750] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 102, in catalog
    time.sleep(15)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-26 16:20:12,761] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=assignment, task_id=task_one, execution_date=20241226T161606, start_date=20241226T161847, end_date=20241226T162012
[2024-12-26 16:20:12,796] {process_utils.py:66} INFO - Process psutil.Process(pid=1281, status='terminated', exitcode=1, started='16:18:46') (1281) terminated with exit code 1
